export default [
  "React",
  "Redux",
  "Node",
  "Express",
  "CSS Modules",
  "Typescript",
  "MongoDB",
  "Firebase",
  "Storybook",
  "Jest Testing",
  "Cypress Testing",
  "React Testing Library",
  "CircleCi",
  "Styled Components",
  "Sendgrid & Mailchimp APIs",
  "SanityIo",
  "MixPanel & GA Analytics",
]
